#!/bin/bash
cat <<END
Content-Type: text/plain

END
conducteur=`mysql -uroot -pbananapi -se "SELECT c.Photo FROM Voiture.Instantane i INNER JOIN Voiture.Conducteur c ON i.Conducteur_en_cours = c.id_conducteur ;"`
echo $conducteur;