#!/bin/bash
cat <<END
Content-Type: text/plain

END
conducteur=`mysql -uroot -pbananapi -se "SELECT c.Prenom FROM bdc.Instantane i INNER JOIN bdc.Conducteur c ON i.Conducteur_en_cours = c.id_conducteur ;"`
echo Bienvenue $conducteur;