#!/bin/bash
cat <<END
Content-Type: text/plain

END
tempsConduite=`mysql -uroot -pbananapi -se "SELECT temps_conduite FROM bdc.Instantane ORDER BY Id DESC LIMIT 1";`
pourcent=`echo "$tempsConduite*0.83" | bc -l | cut -d "." -f1`
echo $pourcent;
