#!/bin/bash
#Calcul de la date et heure
date=`gpspipe -w | head -5 | grep TPV | cut -d, -f5 | cut -c9-18 | head -1`
annee=`echo $date | cut -c1-4`
mois=`echo $date | cut -c6-7`
jour=`echo $date | cut -c9-10`
heure=`gpspipe -w | head -5 | grep TPV | cut -d, -f5 | cut -c20-27 | head -1`
heureheure=`echo $heure | cut -c1-2`
min=`echo $heure | cut -c4-5`
#echo $heureheure
if [[ $Pays -eq "France" ]]
then
        let heureheure++
        #echo $heureheure
        if [[ $heureheure -eq "24" ]]
        then
                heureheure=00
                let jour++
        fi
fi
date=`echo $jour/$mois/$annee $heureheure:$min`
cat <<END
Content-Type: text/plain

END
echo $date;

