#!/bin/bash
cat <<END
Content-Type: text/plain

END
tempsConduite=`mysql -uroot -pbananapi -se "SELECT c.Temps_conduite_partiel FROM Voiture.Conducteur c INNER JOIN Voiture.Instantane i ON i.Conducteur_en_cours = c.id_conducteur;"`
pourcent=`echo "$tempsConduite*0.83" | bc -l | cut -d "." -f1`;
echo $pourcent;